In [1]:
import pandas as pd
from foodscraper.config import GOOGLE_MAPS_DATASETS
import pprint
import json

In [2]:
pd.set_option("display.max.columns", None)
pd.set_option("display.max.rows", None)

In [3]:
# df = pd.read_json(GOOGLE_MAPS_DATASETS / "mini-box_20260311_101610.json")
df = pd.read_json(GOOGLE_MAPS_DATASETS / "copenhagen-bounds_20260501_211500.json")
# df = pd.read_json(GOOGLE_MAPS_DATASETS / "only-two.json")

df.head()

,name,id,types,nationalPhoneNumber,internationalPhoneNumber,formattedAddress,addressComponents,plusCode,location,viewport,rating,googleMapsUri,websiteUri,regularOpeningHours,utcOffsetMinutes,adrFormatAddress,businessStatus,priceLevel,userRatingCount,iconMaskBaseUri,iconBackgroundColor,displayName,primaryTypeDisplayName,takeout,delivery,dineIn,reservable,servesBreakfast,servesLunch,servesDinner,servesBeer,servesWine,servesBrunch,currentOpeningHours,currentSecondaryOpeningHours,regularSecondaryOpeningHours,primaryType,shortFormattedAddress,reviews,photos,outdoorSeating,liveMusic,menuForChildren,servesCocktails,servesDessert,servesCoffee,goodForChildren,allowsDogs,restroom,goodForGroups,goodForWatchingSports,paymentOptions,parkingOptions,accessibilityOptions,addressDescriptor,googleMapsLinks,priceRange,timeZone,postalAddress,googleMapsTypeLabel,containingPlaces,curbsidePickup,servesVegetarianFood,editorialSummary,fuelOptions
0,places/ChIJ6eXKTWdDUkYR7k5XjV6Ju-0,ChIJ6eXKTWdDUkYR7k5XjV6Ju-0,"[restaurant, inn, lodging, food, point_of_inte...",48 18 30 01,+45 48 18 30 01,"Bygaden 30, 3660 Ganløse, Denmark","[{'longText': '30', 'shortText': '30', 'types'...","{'globalCode': '9F7JQ7V7+94', 'compoundCode': ...","{'latitude': 55.793493999999995, 'longitude': ...","{'low': {'latitude': 55.792122919708504, 'long...",4.4,https://maps.google.com/?cid=17130436646825053...,http://ganlosekro.dk/,"{'openNow': True, 'periods': [{'open': {'day':...",120,"<span class=""street-address"">Bygaden 30</span>...",OPERATIONAL,PRICE_LEVEL_MODERATE,1390.0,https://maps.gstatic.com/mapfiles/place_api/ic...,#FF9E67,"{'text': 'Ganløse Kro', 'languageCode': 'da'}","{'text': 'Restaurant', 'languageCode': 'en-US'}",1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,"{'openNow': True, 'periods': [{'open': {'day':...","[{'openNow': False, 'periods': [{'open': {'day...","[{'openNow': False, 'periods': [{'open': {'day...",restaurant,"Bygaden 30, Ganløse",[{'name': 'places/ChIJ6eXKTWdDUkYR7k5XjV6Ju-0/...,[{'name': 'places/ChIJ6eXKTWdDUkYR7k5XjV6Ju-0/...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,"{'acceptsCreditCards': True, 'acceptsDebitCard...","{'freeParkingLot': True, 'freeStreetParking': ...","{'wheelchairAccessibleParking': True, 'wheelch...",{'landmarks': [{'name': 'places/ChIJM3IMIl5DUk...,{'directionsUri': 'https://www.google.com/maps...,"{'startPrice': {'currencyCode': 'DKK', 'units'...",{'id': 'Europe/Copenhagen'},"{'regionCode': 'DK', 'languageCode': 'en-US', ...","{'text': 'Restaurant', 'languageCode': 'en-US'}",NaN,NaN,NaN,NaN,NaN
1,places/ChIJ21qBwtRDUkYRGBAxnmFfg10,ChIJ21qBwtRDUkYRGBAxnmFfg10,"[restaurant, food, point_of_interest, establis...",93 92 21 42,+45 93 92 21 42,"Bygaden 7, 3660 Ganløse, Denmark","[{'longText': '7', 'shortText': '7', 'types': ...","{'globalCode': '9F7JQ7R7+C8', 'compoundCode': ...","{'latitude': 55.7911146, 'longitude': 12.263354}","{'low': {'latitude': 55.789767219708494, 'long...",4.7,https://maps.google.com/?cid=67383343403468759...,http://www.hjaltesburesoe.dk/,"{'openNow': False, 'periods': [{'open': {'day'...",120,"<span class=""street-address"">Bygaden 7</span>,...",OPERATIONAL,PRICE_LEVEL_MODERATE,153.0,https://maps.gstatic.com/mapfiles/place_api/ic...,#FF9E67,"{'text': 'Hjaltes Ganløse', 'languageCode': 'da'}","{'text': 'Restaurant', 'languageCode': 'en-US'}",1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,"{'openNow': False, 'periods': [{'open': {'day'...",NaN,NaN,restaurant,"Bygaden 7, Ganløse",[{'name': 'places/ChIJ21qBwtRDUkYRGBAxnmFfg10/...,[{'name': 'places/ChIJ21qBwtRDUkYRGBAxnmFfg10/...,1.0,0.0,1.0,NaN,1.0,1.0,1.0,NaN,1.0,1.0,0.0,"{'acceptsCreditCards': True, 'acceptsDebitCard...","{'freeParkingLot': True, 'freeStreetParking': ...",NaN,{'landmarks': [{'name': 'places/ChIJm0zBFl5DUk...,{'directionsUri': 'https://www.google.com/maps...,"{'startPrice': {'currencyCode': 'DKK', 'units'...",{'id': 'Europe/Copenhagen'},"{'regionCode': 'DK', 'languageCode': 'en-US', ...","{'text': 'Brasserie', 'languageCode': 'en-US'}",NaN,NaN,NaN,NaN,NaN
2,places/ChIJV5-mcl5DUkYRbdj-CHc26vo,ChIJV5-mcl5DUkYRbdj-CHc26vo,"[pizza_restaurant, restaurant, food, point_of_...",48 18 41 02,+45 48 18 41 02,"Vestergade 1C, 3660 Ganløse, Denmark","[{'longText': '1C', 'shortText': '1C', 'types'...","{'globalCode': '9F7JQ7R7+C5', 'compoundCode': ...","{'latitude': 55.791086, 'longitude': 12.262934...","{'low': {'latitude': 55.7898042197085, 'longit...",4.1,https://maps.google.com/?cid=18080323538912204...,http://ganløse-pizzaria.dk/,"{'openNow': False, 'periods': [{'open': {'day'...",120,"<span class=""street-address"">Vestergade 1C</sp...",OPERATIONAL,NaN,106.0,https://maps.gstatic.com/mapfiles/place_api/ic...,#FF9E67,"{'text': 'Ganløse Pizzaria & Grillbar', 'langu...","{'text': 'Pizza Restaurant', 'languageCode': '...",1.0,NaN,1.0,1.0,NaN,1.0,1.0,NaN,NaN,0.0,"{'openNow': False, 'periods': [{'open': {'day'...",NaN,NaN,pizza_restaurant,"Vestergade 1C, Ganløse",[{'name': 'places/ChIJV5-mcl5DUkYRbdj-CHc26vo/...,[{'name': 'places/ChIJV5-mcl5DUkYRbdj-CHc26vo/...,1.0,0.0,1.0,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,"{'acceptsCreditCards': True, 'acceptsDebitCard...",{'freeStreetParking': True},NaN,{'landmarks': [{'name': 'places/ChIJm0zBFl5DUk...,{'directionsUri': 'https://www.google.com/maps...,"{'startPrice': {'currencyCode': 'DKK', 'units'...",{'id': 'Europe/Copenhagen'},"{'regionCode': 'DK', 'languageCode': 'en-US', ...","{'text': 'Pizza Restaurant', 'languageCode': '...",NaN,NaN,NaN,NaN,NaN
3,places/ChIJi3WmCDNDUkYR3RiZaGcapv4,ChIJi3WmCDNDUkYR3RiZaGcapv4,"[meal_takeaway, restaurant, food, point_of_int...",20 72 16 26,+45 20 72 16 26,"Østergade 2, 3660 Ganløse, Denmark","[{'longText': '2', 'shortText': '2', 'types': ...","{'globalCode': '9F7JQ7R7+GF', 'compoundCode': ...","{'latitude': 55.791314299999996, 'longitude': ...","{'low': {'latitude': 55.78997591970849, 'longi...",2.0,https://maps.google.com/?cid=18349382763206482...,https://www.guldkyllingen.dk/grilltruck/roskil...,"{'openNow': False, 'periods': [{'open': {'day'...",120,"<span class=""street-address"">Østergade 2</span...",OPERATIONAL,NaN,1.0,https://maps.gstatic.com/mapfiles/place_api/ic...,#FF9E67,"{'text': 'GuldKyllingen Ganløse', 'languageCod...","{'text': 'Takeout Restaurant', 'languageCode':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'openNow': False, 'periods': [{'open': {'day'...",NaN,NaN,meal_takeaway,"Østergade 2, Ganløse",[{'name': 'places/ChIJi3WmCDNDUkYR3RiZaGcapv4/...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,"{'acceptsCreditCards': True, 'acceptsDebitCard...",{'freeStreetParking': True},NaN,{'landmarks': [{'name': 'places/ChIJm0zBFl5DUk...,{'directionsUri': 'https://www.google.com/maps...,NaN,{'id': 'Europe/Copenhagen'},"{'regionCode': 'DK', 'languageCode': 'en-US', ...","{'text': 'Takeout Restaurant', 'languageCode':...",[{'name': 'places/ChIJm0zBFl5DUkYRFLuACSglRi0'...,NaN,NaN,NaN,NaN
4,places/ChIJ7YUAyQFFUkYR8jfTnIYJ8cc,ChIJ7YUAyQFFUkYR8jfTnIYJ8cc,"[restaurant, banquet_hall, event_venue, food, ...",42 95 22 40,+45 42 95 22 40,"Christianshøjvej 22, 3500 Værløse, Denmark","[{'longText': '22', 'shortText': '22', 'types'...","{'globalCode': '9F7JQ8RF+FJ', 'compoundCode': ...","{'latitude': 55.791139099999995, 'longitude': ...","{'low': {'latitude': 55.7898500697085, 'longit...",4.0,https://maps.google.com/?cid=14407307156696283...,http://spisehusetværløse.dk/,"{'openNow': False, 'periods': [{'open': {'day'...",120,"<span class=""street-address"">Christianshøjvej ...",OPERATIONAL,NaN,5.0,https://maps.gstatic.com/mapfiles/place_api/ic...,#FF9E67,"{'text': 'Spisehuset Værløse', 'languageCode':...","{'text': 'Restaurant', 'languageCode': 'en-US'}",1.0,0.0,1.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,"{'openNow': False, 'periods': [{'open': {'day'...",NaN,NaN,restaurant,"Christianshøjvej 22, Værløse",[{'name': 'places/ChIJ7YUAyQFFUkYR8jfTnIYJ8cc/...,[{'name': 'places/ChIJ7YUAyQFFUkYR8jfTnIYJ8cc/...,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,"{'acceptsCreditCards': True, 'acceptsDebitCard...","{'freeParkingLot': True, 'freeStreetParking': ...","{'wheelchairAccessibleParking': True, 'wheelch...",{'landmarks': [{'name': 'places/ChIJ3W0p2uBEUk...,{'directionsUri': 'https://www.google.com/maps...,"{'startPrice': {'currencyCode': 'DKK', 'units'...",{'id': 'Europe/Copenhagen'},"{'regionCode': 'DK', 'languageCode': 'en-US', ...","{'text': 'Restaurant', 'languageCode': 'en-US'}",[{'name': 'places/ChIJ3W0p2uBEUkYRo8UZPGrHfK0'...,0.0,NaN,NaN,NaN

In [4]:
df["name"] = df["displayName"].apply(lambda d: d["text"])
halifax = df[df["name"] == "Halifax"]
halifax

,name,id,types,nationalPhoneNumber,internationalPhoneNumber,formattedAddress,addressComponents,plusCode,location,viewport,rating,googleMapsUri,websiteUri,regularOpeningHours,utcOffsetMinutes,adrFormatAddress,businessStatus,priceLevel,userRatingCount,iconMaskBaseUri,iconBackgroundColor,displayName,primaryTypeDisplayName,takeout,delivery,dineIn,reservable,servesBreakfast,servesLunch,servesDinner,servesBeer,servesWine,servesBrunch,currentOpeningHours,currentSecondaryOpeningHours,regularSecondaryOpeningHours,primaryType,shortFormattedAddress,reviews,photos,outdoorSeating,liveMusic,menuForChildren,servesCocktails,servesDessert,servesCoffee,goodForChildren,allowsDogs,restroom,goodForGroups,goodForWatchingSports,paymentOptions,parkingOptions,accessibilityOptions,addressDescriptor,googleMapsLinks,priceRange,timeZone,postalAddress,googleMapsTypeLabel,containingPlaces,curbsidePickup,servesVegetarianFood,editorialSummary,fuelOptions
297,Halifax,ChIJ58FXiGxOUkYRo-Fu2gs9RBM,"[hamburger_restaurant, american_restaurant, re...",82 30 43 19,+45 82 30 43 19,"Handelstorvet, 2800 Kongens Lyngby, Denmark","[{'longText': 'Handelstorvet', 'shortText': 'H...","{'globalCode': '9F7JQGC4+27', 'compoundCode': ...","{'latitude': 55.7700091, 'longitude': 12.50568...","{'low': {'latitude': 55.76860476970851, 'longi...",4.0,https://maps.google.com/?cid=13883017062555897...,http://www.halifax.dk/,"{'openNow': True, 'periods': [{'open': {'day':...",120,"<span class=""street-address"">Handelstorvet</sp...",OPERATIONAL,PRICE_LEVEL_MODERATE,811.0,https://maps.gstatic.com/mapfiles/place_api/ic...,#FF9E67,"{'text': 'Halifax', 'languageCode': 'en'}","{'text': 'Hamburger Restaurant', 'languageCode...",1.0,NaN,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,"{'openNow': True, 'periods': [{'open': {'day':...",NaN,NaN,hamburger_restaurant,"Handelstorvet, Kongens Lyngby",[{'name': 'places/ChIJ58FXiGxOUkYRo-Fu2gs9RBM/...,[{'name': 'places/ChIJ58FXiGxOUkYRo-Fu2gs9RBM/...,1.0,0.0,1.0,NaN,1.0,1.0,1.0,0.0,1.0,1.0,0.0,"{'acceptsCreditCards': True, 'acceptsDebitCard...","{'paidParkingLot': True, 'paidStreetParking': ...","{'wheelchairAccessibleParking': True, 'wheelch...",{'landmarks': [{'name': 'places/ChIJrZ3HfGtOUk...,{'directionsUri': 'https://www.google.com/maps...,"{'startPrice': {'currencyCode': 'DKK', 'units'...",{'id': 'Europe/Copenhagen'},"{'regionCode': 'DK', 'languageCode': 'en-US', ...","{'text': 'Hamburger Restaurant', 'languageCode...",[{'name': 'places/ChIJrZ3HfGtOUkYRBtq_sBrK94I'...,NaN,1.0,{'text': 'Handcrafted burgers & bowls made wit...,NaN

In [5]:
halifax = halifax[["id", "name", "formattedAddress", "websiteUri"]]
halifax

,id,name,formattedAddress,websiteUri
297,ChIJ58FXiGxOUkYRo-Fu2gs9RBM,Halifax,"Handelstorvet, 2800 Kongens Lyngby, Denmark",http://www.halifax.dk/

In [6]:
halifax_json = {
  "id": "ChIJ58FXiGxOUkYRo-Fu2gs9RBM",
  "name": "Halifax",
  "formattedAddress": "Handelstorvet, 2800 Kongens Lyngby, Denmark",
  "websiteUri": "http://www.halifax.dk/"
}